### ISSUE TITLE
unexpected token "attrs" in file offline.jade on line 31

### ISSUE THREAD

**Issue by maklaut** [yandex-load/yatank-online#5]
По окончании теста возникает следующая ошибка.

```
2015-07-29 16:59:59,915 [INFO] yandextank.core.tankcore Building HTML report...
2015-07-29 16:59:59,915 [DEBUG] yandextank.core.tankcore Adding artifact file to collect (keep=False): /data/qa/_results/report_dxgVlf.html
2015-07-29 16:59:59,991 [ERROR] yandextank.core.tankcore Failed post-processing plugin <OnlineReportPlugin(Thread-1, stopped daemon 139981118691072)>: unexpected token "attrs" in file offline.jade on line 31
2015-07-29 16:59:59,992 [DEBUG] yandextank.core.tankcore Failed post-processing plugin: Traceback (most recent call last):
  File "/data/qa/venv/lib/python2.6/site-packages/yandextank/core/tankcore.py", line 345, in plugins_post_process
    retcode = plugin.post_process(retcode)
  File "/data/qa/venv/lib/python2.6/site-packages/yatank_OnlineReport/plugin.py", line 97, in post_process
    self.server.render_offline()
  File "/data/qa/venv/lib/python2.6/site-packages/yatank_OnlineReport/server.py", line 129, in render_offline
    return loader.load('offline.jade').generate(cached_data=json.dumps(cached_data))
  File "/data/qa/venv/lib/python2.6/site-packages/tornado/template.py", line 343, in load
    self.templates[name] = self._create_template(name)
  File "/data/qa/venv/lib/python2.6/site-packages/tornado/template.py", line 371, in _create_template
    template = Template(f.read(), name=name, loader=self)
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/ext/tornado/__init__.py", line 82, in __init__
    template_string = process(template_string,filename=name,compiler=Compiler)
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/utils.py", line 228, in process
    block = _parser.parse()
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 46, in parse
    else: block.append(self.parseExpr())
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 84, in parseExpr
    return getattr(self,funcName)()
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 332, in parseTag
    block = self.block()
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 251, in block
    block.append(self.parseExpr())
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 84, in parseExpr
    return getattr(self,funcName)()
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 332, in parseTag
    block = self.block()
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 251, in block
    block.append(self.parseExpr())
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 84, in parseExpr
    return getattr(self,funcName)()
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 332, in parseTag
    block = self.block()
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 251, in block
    block.append(self.parseExpr())
  File "/data/qa/venv/lib/python2.6/site-packages/pyjade/parser.py", line 87, in parseExpr
    (t, self.filename, self.line()))
Exception: unexpected token "attrs" in file offline.jade on line 31
```

Версии софта:

```
$ python -V
Python 2.6.6

$ pip list
argparse (1.3.0)
backports.ssl-match-hostname (3.4.0.2)
certifi (2015.4.28)
docutils (0.12)
futures (3.0.3)
hypchat (0.15)
importlib (1.0.3)
ipaddr (2.1.11)
lockfile (0.10.2)
ordereddict (1.1)
pip (7.1.0)
progressbar (2.3)
psutil (3.1.1)
pudb (2015.3)
Pygments (2.0.2)
pyjade (3.1.0)
python-daemon (2.0.5)
python-dateutil (2.4.2)
pytz (2015.4)
PyYAML (3.11)
requests (2.7.0)
setuptools (18.0.1)
simplejson (3.8.0)
six (1.9.0)
slumber (0.7.1)
TornadIO2 (0.0.4)
tornado (4.2.1)
trollius (2.0)
urwid (1.3.0)
wheel (0.24.0)
winpdb (1.4.8)
yandex-tank-api (0.0.11)
yandex-tank-api-client (0.0.4)
yandextank (1.7.13)
yatank-online (0.0.2)
```

**Comment by melfa** [comment]
Аналогичная ошибка.

**Comment by aamalev** [comment]
можно откатить pyjade до версии 3.0.0.

```
pip install pyjade==3.0.0
```

т.к. 3.1.0 стал подругому понимать теги script и style без точки
